#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SUPABASE_PROJECT_REF="agezrfclusigfqysbxwb"
SUPABASE_CALLBACK="https://${SUPABASE_PROJECT_REF}.supabase.co/auth/v1/callback"

banner "Google OAuth for admin login"
say "Code side is already done: the Google button on /admin/login, the"
say "signInWithOAuth server action, and the /admin/auth/callback route."
say "This wizard covers the two dashboards only you can configure:"
say "Google Cloud Console and the Supabase Auth settings."

# ── Stage 1: OAuth consent screen ──────────────────────────────────────────
stage "Google Cloud: OAuth consent screen"
say "If you already have a Google Cloud project for this site, select it on"
say "the page that opens. Otherwise create a new project first."
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "Choose User type: External, then Create."
step "App name: something recognizable, e.g. \"SVIT Vasad Admin\"."
step "User support email: your own or a shared admin address."
step "Developer contact email: same."
step "Save through the Scopes and Test users screens (defaults are fine —"
step "the default 'email', 'profile', 'openid' scopes are all this needs)."
if confirm "Consent screen created/confirmed?"; then
  note "consent screen ready"
else
  warn "come back to this stage before continuing"
fi

# ── Stage 2: OAuth client ID ───────────────────────────────────────────────
stage "Google Cloud: OAuth client ID"
open_url "https://console.cloud.google.com/apis/credentials"
step "Click + Create credentials → OAuth client ID."
step "Application type: Web application."
step "Name: e.g. \"SVIT Admin — Supabase\"."
step "Under Authorized redirect URIs, add exactly:"
note "  $SUPABASE_CALLBACK"
step "Click Create. A dialog shows the Client ID and Client Secret — copy"
step "both (you can also find them later on this same credentials page)."
ask GOOGLE_OAUTH_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_OAUTH_CLIENT_SECRET "Paste the Client Secret:"

# ── Stage 3: Enable the provider in Supabase ───────────────────────────────
stage "Supabase: enable Google provider"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/providers"
step "Find Google in the provider list and toggle it on."
step "Paste the Client ID into 'Client ID (for OAuth)'."
step "Paste the Client Secret into 'Client Secret (for OAuth)'."
step "Click Save."
if confirm "Google provider enabled and saved in Supabase?"; then
  note "provider enabled"
else
  warn "the app's Google button will fail until this is saved"
fi

# ── Stage 4: Redirect URL allow-list ───────────────────────────────────────
stage "Supabase: redirect URL allow-list"
say "Supabase only allows redirecting back to URLs on this allow-list after"
say "the OAuth handshake, so both local dev and production need an entry."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/url-configuration"
step "Under Redirect URLs, add:"
note "  http://localhost:3000/admin/auth/callback"
ask PROD_ORIGIN "Production origin (e.g. https://svitvasad.ac.in), leave blank to skip:"
if [[ -n "$PROD_ORIGIN" ]]; then
  note "  ${PROD_ORIGIN%/}/admin/auth/callback"
  step "Add that URL too."
fi
step "Save."
if confirm "Redirect URLs saved?"; then
  note "redirect URLs saved"
else
  warn "Google sign-in will redirect to an error page until this is saved"
fi

# ── Stage 5: Verify end-to-end ─────────────────────────────────────────────
stage "Verify"
say "Start the dev server if it isn't already running:"
note "  npm run dev"
say "Then:"
step "Visit http://localhost:3000/admin/login"
step "Click 'Sign in with Google' and complete the Google consent screen."
step "Expect a redirect through /admin/auth/callback back to /admin."
note "If the signed-in Google account has no role yet in user_roles, it"
note "will bounce back to /admin/login — that's the existing RBAC gate"
note "working as intended, not a bug. Grant it a role from an existing"
note "admin account (or directly in the user_roles table) to finish."
confirm "Signed in successfully (or confirmed the expected no-role bounce)?"

finish
